import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import OrderState from "@/context/orderContext/orderState";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Restaurant Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <OrderState>{children}</OrderState>
      </body>
    </html>
  );
}
